// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0AUaAWemqJxCJyuQc3NJvr8aKS2DAi6U',
    appId: '1:470329448144:web:3570dbad0d0dc31426b0d5',
    messagingSenderId: '470329448144',
    projectId: 'carecenter-1c1d5',
    authDomain: 'carecenter-1c1d5.firebaseapp.com',
    storageBucket: 'carecenter-1c1d5.firebasestorage.app',
    measurementId: 'G-XTN6Y05NJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAejskMIEJ-d0Upppu9b9_SZKbGxVhPU9s',
    appId: '1:470329448144:android:2583e5f1c9ff9ae226b0d5',
    messagingSenderId: '470329448144',
    projectId: 'carecenter-1c1d5',
    storageBucket: 'carecenter-1c1d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3g7rVaJ0AUQRmnPq0mdIzDI9rEXN-8gQ',
    appId: '1:470329448144:ios:83526e0dbc87b08a26b0d5',
    messagingSenderId: '470329448144',
    projectId: 'carecenter-1c1d5',
    storageBucket: 'carecenter-1c1d5.firebasestorage.app',
    iosBundleId: 'com.example.careCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3g7rVaJ0AUQRmnPq0mdIzDI9rEXN-8gQ',
    appId: '1:470329448144:ios:83526e0dbc87b08a26b0d5',
    messagingSenderId: '470329448144',
    projectId: 'carecenter-1c1d5',
    storageBucket: 'carecenter-1c1d5.firebasestorage.app',
    iosBundleId: 'com.example.careCenter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0AUaAWemqJxCJyuQc3NJvr8aKS2DAi6U',
    appId: '1:470329448144:web:8fec20ba70afa28026b0d5',
    messagingSenderId: '470329448144',
    projectId: 'carecenter-1c1d5',
    authDomain: 'carecenter-1c1d5.firebaseapp.com',
    storageBucket: 'carecenter-1c1d5.firebasestorage.app',
    measurementId: 'G-09H4E830PJ',
  );
}
